### ISSUE TITLE
Can not run first time setup

### ISSUE THREAD

**Issue by laodq** [JKHeadley/rest-hapi-demo#1]
After installed the demo, we can not run first time setup.

hdq@eisbuntu:~/node/examples/rest-hapi-demo$./node_modules/.bin/rest-hapi-cli seed
[19:35:06] Working directory changed to ~/node/examples/rest-hapi-demo/node_modules/rest-hapi

/home/hdq/node/examples/rest-hapi-demo/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/hdq/node/examples/rest-hapi-demo/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/hdq/node/examples/rest-hapi-demo/node_modules/rest-hapi/gulpfile.js:9:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)

=====
ok, fix this issue by "Downgrading to nodejs v 6.11.2 did fix the issue" from tip of project appy.

**Comment by JKHeadley** [comment]
Glad you worked it out 👍
