### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by SaniHaque** [JKHeadley/rest-hapi-demo#2]
`$ ./node_modules/.bin/rest-hapi-cli seed

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'D:\_\_Test\rest-hapi-demo\node_modules\rest-hapiseed.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

D:\_\_Test\rest-hapi-demo\node_modules\rest-hapi\rest-hapi-cli.js:31
        throw err
        ^

Error: Command failed: node ./node_modules/rest-hapiseed.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'D:\_\_Test\rest-hapi-demo\node_modules\rest-hapiseed.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)`

**Comment by JKHeadley** [comment]
@SaniHaque are you using windows?

**Comment by SaniHaque** [comment]
yes

**Comment by JKHeadley** [comment]
I just pushed a possible fix to rest-hapi. Please run `npm install` to get the latest version of rest-hapi and try again.

**Comment by SaniHaque** [comment]
Yes, It's fixed the issue. Thank You.
